// Generated by CoffeeScript 1.7.1
var PlotVariant, PlotVariantCollection,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

PlotVariant = (function(_super) {
  __extends(PlotVariant, _super);

  function PlotVariant() {
    return PlotVariant.__super__.constructor.apply(this, arguments);
  }

  return PlotVariant;

})(Backbone.Model);

PlotVariantCollection = (function(_super) {
  __extends(PlotVariantCollection, _super);

  function PlotVariantCollection() {
    return PlotVariantCollection.__super__.constructor.apply(this, arguments);
  }

  PlotVariantCollection.prototype.model = PlotVariant;

  PlotVariantCollection.prototype.url = function() {
    return "http://commonfloor.local/methods/functions.php?action=load_plot_variants";
  };

  PlotVariantCollection.prototype.setPlotVariantAttributes = function(unitVariantData, project_id) {
    if (unitVariantData == null) {
      unitVariantData = {};
    }
    if (this.length === 0) {
      plotVariantCollection.fetch({
        async: false,
        data: {
          project_id: project_id
        },
        success: (function(_this) {
          return function(collection, response) {
            if (response === 0) {
              return _this.reset();
            }
          };
        })(this)
      });
    }
    return this;
  };

  return PlotVariantCollection;

})(Backbone.Collection);
