// Generated by CoffeeScript 1.7.1
var Settings,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Settings = (function(_super) {
  __extends(Settings, _super);

  function Settings() {
    return Settings.__super__.constructor.apply(this, arguments);
  }

  Settings.prototype.urlRoot = function() {
    return "http://commonfloor.local/methods/functions.php?action=load_settings";
  };

  Settings.prototype.setSettingsAttributes = function(settingsData, project_id) {
    if (settingsData == null) {
      settingsData = {};
    }
    if (jQuery.isEmptyObject(this.toJSON())) {
      settings.fetch({
        async: false,
        data: {
          project_id: project_id
        },
        success: (function(_this) {
          return function(collection, response) {
            if (response === 0) {
              return _this.reset();
            }
          };
        })(this)
      });
    }
    return this;
  };

  return Settings;

})(Backbone.Model);
