// Generated by CoffeeScript 1.7.1
var Unit, UnitCollection,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Unit = (function(_super) {
  __extends(Unit, _super);

  function Unit() {
    return Unit.__super__.constructor.apply(this, arguments);
  }

  return Unit;

})(Backbone.Model);

UnitCollection = (function(_super) {
  __extends(UnitCollection, _super);

  function UnitCollection() {
    return UnitCollection.__super__.constructor.apply(this, arguments);
  }

  UnitCollection.prototype.model = Unit;

  UnitCollection.prototype.url = function() {
    return "http://commonfloor.local/methods/functions.php?action=load_units";
  };

  UnitCollection.prototype.setUnitAttributes = function(unitData, project_id) {
    if (unitData == null) {
      unitData = {};
    }
    if (this.length === 0) {
      unitCollection.fetch({
        async: false,
        data: {
          project_id: project_id
        },
        success: (function(_this) {
          return function(collection, response) {
            if (response === 0) {
              return _this.reset();
            }
          };
        })(this)
      });
    }
    return this;
  };

  return UnitCollection;

})(Backbone.Collection);
